### ISSUE TITLE
Problem installing qtsampleplayer on Ubuntu 16.04

### ISSUE THREAD

**Issue by daemonSlayer** [bitmovin/libdash#9]
On running the command `./cmake-2.8.11.2-Linux-i386/bin/cmake ../ ` , I get this error:
```
Could NOT find LibAV (missing: LIBAV_ROOT_DIR) (found version "ffmpeg
  version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers

  built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
```
I have ffmpeg installed and have tried installing all other lib too. Libdash has successfully compiled but I cant get qtsampleplayer to work. How do I remove this error?

**Comment by ysaidcan** [comment]
How did you solve this issue?

**Comment by daemonslayer** [comment]
I reinstalled ffmpeg, installed `libavre*` that I got through `apt-cache search libav` and found that the cmake was searching for some files in wrong folder. Install everything and then check if cmake is searching in right folders in the system.

**Comment by ysaidcan** [comment]
Thanks. I changed the file CMakeCache.txt . I added the root directory for the libav. I worked.

**Comment by amaklp** [comment]
I changed on /libdash/libdash/qtsampleplayer/build/CMakeCache.txt 
the line
LIBAV_ROOT_DIR:PATH=LIBAV_ROOT_DIR-NOTFOUND
to
LIBAV_ROOT_DIR:PATH=[libdash directory]/libdash/libav

**Comment by rajeshmahalingam** [comment]
This issue is resolved by exporting an environment variable "LIBAVROOT" before do cmake.
$ export LIBAVROOT=<libdash directory>/libdash/libav/
